version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://db_user:db_password@db:3306/db_name
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: symfony_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
